Pulling force field effect with example
djeedai/bevy_hanabi pull request #11
Opened 2022-04-05 14:31 UTC by eliotbo

2022-04-05 19:47 UTC, djeedai requested changes

2022-04-05 19:47 UTC, djeedai commented on examples/force_field.rs
> +                mass: -1.0,
It's a bit awkward to have negative masses, why is that?

2022-04-05 19:47 UTC, djeedai commented on examples/force_field.rs
> +fn record_mouse_events_system(
I'm surprised there's nothing simpler. Can't we just read [`Window.cursor_position()`](https://docs.rs/bevy/latest/bevy/window/struct.Window.html#method.cursor_position) when the user clicks a button?

2022-04-05 19:47 UTC, djeedai commented on src/asset.rs
> +    pub box_lower_bounds: Vec3,
Can you briefly document those please?

2022-04-05 19:47 UTC, djeedai commented on src/asset.rs
> +    modifiers::PullingForceFieldParam, modifiers::FFNUM, Gradient, InitModifier, RenderModifier,
I generally try to stay consistent with the pattern "do not duplicate paths", so `modifiers::{FFNUM, PullingForceFieldParam}` rather than `modifiers::PullingForceFieldParam, modifiers::FFNUM`.

2022-04-05 19:47 UTC, djeedai commented on src/modifiers.rs
> +    /// Mass is proportional to the intensity of the force. Note that the particles_update.wgsl shader will
Isn't it rather the opposite, "the intensity of the force is proportional to the mass"? It's a detail though.

2022-04-05 19:47 UTC, djeedai commented on examples/force_field.rs
> +                mass: -1.0,
I mean, for repulsors it should be negative, but for attractors it should be positive. Since in the case of gravity we should have something like `F = G (m1.m2) / r^2`, so positive attraction force if both masses are positive.

2022-04-05 19:47 UTC, djeedai commented on src/render/particles_update.wgsl
> +    pulling_force.z = 0.0;
Delete? Or provide a way to make it 2D/planar if possible, but this should be 3D by default, since the library uses the 3D rendering path of Bevy.

2022-04-05 19:47 UTC, djeedai commented on src/render/particles_update.wgsl
> +        (vVel + (spawner.accel * sim_params.dt)  + (pulling_force * sim_params.dt))
So technically it's not `pulling_force` but `pulling_acceleration` right? We'd need to multiply by the particle's own mass here if that was really a force. Fine for now though.

2022-04-05 19:47 UTC, djeedai commented on src/render/particles_update.wgsl
> +    ///////////// Start of force field computation /////////////
This entire block should be injected when the modifier is used only. See how it's done for the position init code with `{{INIT_POS_VEL}}` above, and the string replace in `specialize()`:

https://github.com/djeedai/bevy_hanabi/blob/e3ef5af4b3ef9fc286f2ca57a8e1975eda7dcf3a/src/render/mod.rs#L429

2022-04-05 19:47 UTC, djeedai commented on src/render/particles_update.wgsl
> +    vVel = (vPos - temp_vPos) / sim_params.dt;
At the moment, and this is awkward, Bevy will return `Time::delta_seconds() == 0` on first frame. So `dt == 0` happens, and that produces an infinite velocity. I'm afraid that may cause issues.

2022-04-05 20:42 UTC, eliotbo commented on examples/force_field.rs
> +                mass: -1.0,
I must admit that I didn't think about it twice when I wrote the code, but I have now and I recall that when dealing with Coulomb electric forces, the convention is that attractive force is negative because the charges of the two particles are opposite. I really don't mind changing the sign of the mass though, because I do believe users will default to a positive mass and an attractive force. Perhaps the best way to deal with this is having an explicit parameter that is either PointSourceType::Attractive or PointSourceType::Repulsive.

2022-04-05 20:43 UTC, eliotbo commented on examples/force_field.rs
> +fn record_mouse_events_system(
I was planning to eventually use a PerspectiveCamera with bevy_mod_picking, so that we can see the 3d nature of the effect. Thoughts?

2022-04-05 20:44 UTC, eliotbo commented on src/render/particles_update.wgsl
> +        (vVel + (spawner.accel * sim_params.dt)  + (pulling_force * sim_params.dt))
I guess it's in a state of ambiguity for the time being, since the particles are without mass. I'll change it though since acceleration would be more future proof, although we will have to be careful if particle mass is ever implemented. I'll leave a comment for posterity.

2022-04-05 20:46 UTC, eliotbo commented on examples/force_field.rs
> +fn record_mouse_events_system(
bevy_mod_picking might be overkill, but the question about the PerspectiveCamera remains.

2022-04-05 20:48 UTC, eliotbo commented on examples/force_field.rs
> +                mass: -1.0,
ForceSourceType might be a better name.

2022-04-05 20:51 UTC, djeedai commented on examples/force_field.rs
> +                mass: -1.0,
That makes sense. My guess is that gravity-like forces is more common than Coulomb so users might tend to be more familiar with positive forces for attractors. `ForceSourceType` sounds ok to me, but that would be an enum right? So that means you'd need to verify that both variant only take a positive "absolute" value, and internally set the sign correctly? And can we add a bypass via `From<f32>` for power users who know to set a positive attraction force and negative repulsion one (that might be easier to store/manipulate than an enum).

2022-04-05 20:54 UTC, djeedai commented on examples/force_field.rs
> +fn record_mouse_events_system(
Yes perspective camera makes sense, only reason it's not there yet is I was being lazy. Ideally if there's a create to control the camera easily to fly around etc. we can use that. `bevy_mod_picking` might be overkill as we don't really "pick" anything, but if that simplifies the examples and avoid littering them with complex 3D projection code that's irrelevant for what the example is trying to demo, then I'm all for it :)

2022-04-06 02:08 UTC, eliotbo commented on examples/force_field.rs
> +                mass: -1.0,
> and internally set the sign correctly?

yes, that right

Could you explain with code what the bypass would look like? Do you mean having the field `force_sign: f32` in `PullingForceFieldParam`?

At the moment, I've settled for

```
PullingForceFieldParam {
...,
change_force_to_repulsive: bool,
}

impl Into<ForceFieldStd430> for PullingForceFieldParam {
    fn into(self) -> ForceFieldStd430 {
        ForceFieldStd430 {
            ...
            force_sign: if self.change_force_to_repulsive { -1.0 } else { 1.0 },
        }
    }
}
```

let me know, I am not overly attached to this code :)

2022-04-06 17:24 UTC, eliotbo commented on examples/force_field.rs
> +fn record_mouse_events_system(
I'm using smooth-bevy-cameras for orbiting the camera. I didn't need bevy_mod_picking after all. Turning mouse position into world position in 3d turns out to be really simple if you only have a camera orbiting the origin.

2022-04-06 21:21 UTC, djeedai requested changes
This is getting there, I tried the new example it looks super cool, thanks for the hard work!

2022-04-06 21:21 UTC, djeedai commented on src/modifiers.rs
> +    /// For a attracting/repulsing force, this is the maximum radius of the sphere of influence, outside of which
> // For a attracting/repulsing force

This is all there is left though, since you removed constant ones, no?

2022-04-06 21:21 UTC, djeedai commented on src/modifiers.rs
> +    pub fn new(point_attractors: Vec<ForceFieldParam>) -> Self {
Maybe
```suggestion
    pub fn new(point_attractors: &[ForceFieldParam]) -> Self {
```
is more generic/useable? Ideally even `impl IntoIter<ForceFieldParam>` is the most generic way, since all we need here is an iterator.

2022-04-06 21:21 UTC, djeedai commented on src/render/force_field_code.wgsl
> +    // // works anyways, needs investigation
This is likely because the spawner sets a non-zero velocity and it's never touched after, no?

2022-04-06 22:26 UTC, eliotbo commented on src/render/force_field_code.wgsl
> +    // // works anyways, needs investigation
I really don't know. I checked whether `dt` was zero-valued or not on the first frame, and indeed it was.

2022-04-06 22:26 UTC, eliotbo commented on src/modifiers.rs
> +    pub fn new(point_attractors: Vec<ForceFieldParam>) -> Self {
Good idea!

2022-04-06 22:31 UTC, eliotbo commented on src/render/force_field_code.wgsl
> +                (0.0000001 + pow(distance, f32(spawner.force_field[kk].force_type)));
amen to that!

2022-04-07 07:47 UTC, djeedai approved these changes

2022-04-07 07:59 UTC, merged