Added 2D camera support
djeedai/bevy_hanabi pull request #18
Opened 2022-04-09 18:47 UTC by josh65536

For now, exactly one of the features "2d" and "3d" must be enabled.

2022-04-10 09:50 UTC, djeedai requested changes
Thanks @josh65536 that's awesome! Some minor changes, mainly the question about disabling depth buffer in 2D. But looks good otherwise!

2022-04-10 09:50 UTC, djeedai commented on README.md
> +If you're using a 2D camera, add the "2d" feature instead.
```suggestion
If you're using a 2D camera, add the `2d` feature instead.
```

2022-04-10 09:50 UTC, djeedai commented on README.md
> +Add the `bevy_hanabi` dependency to Cargo.toml:
```suggestion
Add the `bevy_hanabi` dependency to `Cargo.toml`:
```

2022-04-10 09:50 UTC, djeedai commented on README.md
> +  - [ ] Mixed 3D camera and 2D camera support
I'm not sure what that means / if that's even possible?

2022-04-10 09:50 UTC, djeedai commented on src/lib.rs
> +compile_error!("Enable either the 2d or 3d feature.");
```suggestion
compile_error!("Enable either the '2d' or '3d' feature.");
```

2022-04-10 09:50 UTC, djeedai commented on src/lib.rs
> +compile_error!("Disable either the 2d or 3d feature. Both at the same time is not supported.");
```suggestion
compile_error!("Disable either the '2d' or '3d' feature. Both at the same time is not supported.");
```

2022-04-10 09:50 UTC, djeedai commented on src/render/mod.rs
> +            depth_stencil: None,
That's a bit arguable no? Just because it's 2D doesn't mean users don't want a depth buffer, do they? Why this choice?

2022-04-10 09:57 UTC, djeedai commented on src/render/mod.rs
> +            depth_stencil: None,
Ah just saw on Discord this is a Bevy limitation. Let's leave like that for now then. It's a bit surprising though.

2022-04-10 17:44 UTC, josh65536 commented on README.md
> +  - [ ] Mixed 3D camera and 2D camera support
I was thinking that we may want to support a game that uses a 3D camera and a 2D camera in different places/times, but now that I think about it, it may be better to just have them double-depend on `bevy_hanabi` with different features.

2022-04-11 17:03 UTC, djeedai approved these changes

2022-04-11 17:03 UTC, merged