Add a global time scale for all effects
djeedai/bevy_hanabi pull request #267
Opened 2024-01-14 17:01 UTC by jannik4

Add a global time scale for all effects. Currently very WIP. Probably needs:
- Some tests/examples
- More docs
- ...

Closes #239. Pausing should be possible by setting `EffectTimeScale` to zero.

2024-01-15 18:44 UTC, djeedai commented on src/render/mod.rs
> +    sim_params.delta_time = (***time_scale * time.delta_seconds_f64()) as f32;
Isn't this essentially re-implementing partially `Time<T>`? Could we instead simply use `Time<EffectSimulationTime>`? See my comment on #239 for details.

2024-01-15 21:31 UTC, jannik4 commented on src/render/mod.rs
> +    sim_params.delta_time = (***time_scale * time.delta_seconds_f64()) as f32;
Looks like yes, just had a proper look at `Time<T>` for the first time. Something like `Time<EffectSimulation>` seems like a good idea then.

I would be happy to try to implement this. I can then imagine a total of three "Time/Delta Time" values:

- `sim_params.real_time`: From `Time<Real>`
- `sim_params.virtual_time`: From `Time<Virtual>`
- `sim_params.time`: From `Time<EffectSimulation>`

Where `Time<EffectSimulation>` is then a scaled version of `Time<Virtual>`. This would allow pausing/scaling time by both bevy's `Time<Virtual>` and by hanabi's `Time<EffectSimulation>`. All built in shader code would then use `sim_params.time`, but users can also use the other two versions.

This should be quite flexible. (But also adds a bit complexity)

2024-01-15 22:00 UTC, jannik4 commented on src/render/mod.rs
> +    sim_params.delta_time = (***time_scale * time.delta_seconds_f64()) as f32;
Implementation wise this seems pretty straight forward:

- bevy provides [virtual_time_system](https://docs.rs/bevy/latest/bevy/time/fn.virtual_time_system.html)
- So we can then just update `Time<EffectSimulation>` after that by `Time<Virtual>::delta()`

2024-01-16 07:25 UTC, djeedai commented on src/render/mod.rs
> +    sim_params.delta_time = (***time_scale * time.delta_seconds_f64()) as f32;
Sounds all good to me. `SimParams` is small and uploaded once per frame, not per effect, so I'm totally fine adding more stuffs to it (including real/virtual times). Chances are, with DMA copy alignment (256 bytes?) we're already copying zeros instead at the minute, so it will make no difference.

2024-02-17 11:45 UTC, djeedai requested changes
This looks good overall but there's a number of small issues I think. Maybe some test would help validate the behavior here? Thanks!

2024-02-17 11:45 UTC, djeedai commented on src/render/mod.rs
> +    virtual_time: Extract<Res<Time<EffectSimulation>>>,
Wrong times here?

2024-02-17 11:45 UTC, djeedai commented on src/time.rs
> +pub trait EffectSimulationTime {
Why do we need this trait?

2024-02-17 11:45 UTC, djeedai commented on src/time.rs
> +    };
Maybe wrap into a `relative_speed()` function that checks `paused` internally, for clarity?

2024-02-17 11:45 UTC, djeedai commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
I don't understand, `effective_speed` was read directly from the simulation clock, and is re-written back into it, but doesn't seem to be affected in any way by the virtual clock. Is this missing some `* virtual_speed` somewhere?

2024-02-17 11:45 UTC, djeedai commented on src/spawn.rs
> +        app.init_resource::<Time<EffectSimulation>>();
I'd assume this *also* needs `init_resource::<Time>()` since we need the base `Virtual` time. This is an emty app for testing, so won't have `Time` by default.

2024-02-17 13:31 UTC, jannik4 commented on src/time.rs
> +impl EffectSimulationTime for Time<EffectSimulation> {
Unfortunately not, because `Time<T>` is a foreign type

2024-02-17 13:32 UTC, jannik4 commented on src/time.rs
> +pub trait EffectSimulationTime {
See above

2024-02-17 13:33 UTC, jannik4 commented on src/render/mod.rs
> +    virtual_time: Extract<Res<Time<EffectSimulation>>>,
Fixed

2024-02-17 13:33 UTC, jannik4 commented on src/spawn.rs
> +        app.init_resource::<Time<EffectSimulation>>();
`Time` is not need as the time is advanced manually in the tests. (It was the same before, I didn't change anything there)

2024-02-17 13:39 UTC, jannik4 commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
`effective_speed` is a local variable a few lines above and is set depending on `paused` and `relative_speed`.

`effective_speed` is just zero when paused and `relative_speed` when running. It is and should be independent of the virtual time.

The only thing that is dependent on the virtual time is the resulting delta for that frame.

2024-02-17 13:42 UTC, jannik4 commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
This is pretty much the same as here (without the extra clamping):

https://github.com/bevyengine/bevy/blob/abb8c353f49a6fe9e039e82adbe1040488ad910a/crates/bevy_time/src/virt.rs#L229-254

2024-02-17 13:50 UTC, jannik4 commented on src/time.rs
> +    };
There is already a `relative_speed()` function that always returns the relative speed regardless of `paused`. This is exactly what bevy does for `Time<Virtual>`. I think it makes sense to do it the same way.

2024-02-17 16:16 UTC, djeedai commented on src/time.rs
> +impl EffectSimulationTime for Time<EffectSimulation> {
I still don't understand how all that works. What the relation with your trait?

2024-02-17 16:31 UTC, djeedai commented on src/time.rs
> +impl EffectSimulationTime for Time<EffectSimulation> {
Oh ok I think I got it. It's a bit too clever.

2024-02-17 16:33 UTC, djeedai commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
Yes but `Virtual` is a self-contained clock whereas this one is based on `Virtual`. What is strange to me is that we document "the final speed is the product of the two clock speeds" but then when we calculate we only store this clock speed in `effective_speed`, not the product. So it's "effective" because it takes into account pausing, but it's still not "effective" as in being the final value used in practice.

2024-02-17 16:34 UTC, djeedai commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
You can't compare with Bevy code, there's no clock in Bevy which is relative to another clock as far as I know.

2024-02-17 16:43 UTC, jannik4 commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
Sure, `Time<Virtual>` is based on `Time<Real>`: https://github.com/bevyengine/bevy/blob/abb8c353f49a6fe9e039e82adbe1040488ad910a/crates/bevy_time/src/virt.rs#L271-279

2024-02-17 16:44 UTC, jannik4 commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
Most of the time code is literally copy-pasted from `Time<Virtual>` and adapted (e.g. remove clamping).

2024-02-17 16:51 UTC, jannik4 commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
Ah, I think I see your point: Because `Time<Virtual>` already has time scaling.

2024-02-17 16:57 UTC, jannik4 commented on src/time.rs
> +    effect_simulation.context_mut().effective_speed = effective_speed;
This should fix it: [1f9a23e](https://github.com/djeedai/bevy_hanabi/pull/267/commits/1f9a23e81571a2a2afc002643eb30452c1d2c99a)

2024-02-26 01:12 UTC, jannik4 commented
Rebased on main and added a test for the effect simulation time. Could you take another look at this, @djeedai?

2024-03-03 09:58 UTC, djeedai approved these changes
Looks all good, thanks for the update!

2024-03-03 09:58 UTC, djeedai commented on src/spawn.rs
> +        app.init_resource::<Time<EffectSimulation>>();
Ah ok and we don't insert the `effect_simulation_time_system` system so we don't need to read `Time<Virtual>`.

2024-03-03 09:58 UTC, djeedai commented on src/time.rs
> +    /// Returns `0.0` if the either [`Time<Virtual>`](Virtual) or
```suggestion
    /// Returns `0.0` if either the [`Time<Virtual>`](Virtual) or the
```

2024-03-04 07:11 UTC, djeedai approved these changes

2024-03-05 18:53 UTC, merged