Implement particle groups, enabling simple particle trails.
djeedai/bevy_hanabi pull request #296
Opened 2024-03-05 10:05 UTC by pcwalton

This commit essentially allows multiple effects to share the same underlying buffer. Such sub-effects are known as *particle groups*. An effect may have up to 32 particle groups, each with its own capacity. Every modifier specifies which particle groups it affects. Spawners always spawn into particle group 0; this restriction was implemented for simplicity and can be lifted later.

A new modifier has been added, `CloneModifier`. This allows particles to be duplicated into a group on a fixed rate. By cloning particles into a group, particle trails can be created.

It's intended that a node graph can be layered on top of particle groups in the future. Particle groups are the most efficient way I can think of to implement node graphs in any case, so this seems to me to be a step toward a node-based editor.

Currently, init modifiers don't run on cloned particles. Their age is, however, reset to 0 if present, as this is typically the most useful behavior.

Internally, each particle group receives its own update and render invocation. This reduces branching in both shaders, simplifies much of the bookkeeping, and enables ribbon rendering for trails in the future (needed for weapon effects, etc.)

The new `worms` example illustrates how trails can be produced with this groups feature.

This PR obsoletes #288. Feedback is very welcome!

2024-03-05 10:07 UTC, pcwalton commented
Here's what the example looks like:

<img width="963" alt="Screenshot 2024-03-05 020706" src="https://github.com/djeedai/bevy_hanabi/assets/157897/732f1fa2-d226-4736-a58b-4509bc33c649">

2024-03-05 17:51 UTC, pcwalton commented
Oh, that limit of 4 dynamic offsets is terribly annoying.

2024-03-05 18:55 UTC, djeedai commented
> Oh, that limit of 4 dynamic offsets is terribly annoying. I'll have to think of how to work around it.

This is if I remember the default for "downlevel" in wgpu, and therefore is expected to be a conservative value for Web. I don't know how many users we'd lose (especially on Web) by raising that limit, but if possible I'd really like to avoid doing so. Let me know if I can help (discussion, review, ...) find a solution.

2024-03-06 00:45 UTC, pcwalton commented
CI looks good now. I worked around the dynamic offsets limit by switching to separate per-effect bind groups for init and update. This is a bit unfortunate, but shouldn't affect performance much since we aren't batching anyhow.

2024-03-09 13:22 UTC, djeedai requested changes
I didn't finish, and most comments are minor in the grand scheme of things ;) but I took the `worms` example and added a loop around it, to spawn 2 similar worms effects, except one has double the particle size (so we can see which is which). Unfortunately, the second effect has no trail, so there's a bug. See how the bigger head particles have no trail.

![image](https://github.com/djeedai/bevy_hanabi/assets/6532395/15f3ae78-f713-43c4-89b5-42adbc3d0445)

2024-03-09 20:53 UTC, pcwalton commented on src/render/mod.rs
> -    pub base_index: u32,
Yep, you were using the OpenGL indirect layout, not the Vulkan one. They're different, weirdly :(

2024-03-09 20:59 UTC, pcwalton commented on src/render/batch.rs
>  }
I had to remove it because I couldn't see a way to batch effects together anymore. The shader needs to know the single effect it's part of to fetch its metadata from the storage buffers. The only alternative I could think of was to store an effect ID with every particle, but that'd add so much memory traffic in the indirect shader I suspected that would lose most of the time.

Batching doesn't seem that helpful for big particle systems, but maybe for small ones like the single-particle system that I envision for weapon trails it could help. I feel like it'd have to be totally redesigned though.

2024-03-09 21:01 UTC, pcwalton commented on src/modifier/clone.rs
> +            context.main_code += &format!("{func}(&particle);", func = func_name);
Yeah, I added the `rate = 0` feature mainly because of ribbons, where "particles" represent vertices in the line, and I figured lots of games would want to spawn as many of those as possible to get the smoothest lines, which is one per frame in the current implementation.

2024-03-09 21:04 UTC, pcwalton commented on src/modifier/clone.rs
> +pub struct CloneModifier {
Sure. I think that we may actually want to have a list of attributes in this modifier so that the user can set "Copy" or "Set to Value", but I'll leave that to a followup.

2024-03-09 22:59 UTC, pcwalton commented on src/render/vfx_common.wgsl
> +    effect_index: u32,
It's the global index of the effect: 0 for the first effect, 1 for the second effect, etc.

2024-03-10 00:45 UTC, pcwalton commented on src/modifier/clone.rs
> +                let {multiple_count} = max(0, i32(floor({b} / f32({m}))) - i32(ceil(({b} - {delta}) / f32({m}))) + 1);
Removed it

2024-03-10 00:50 UTC, pcwalton commented on src/asset.rs
> +        self.init_modifiers.push(GroupedModifier {
Yeah, that's confusing behavior since init modifiers won't run for particles that aren't in group 0. I clarified this in the docs and set `groups` to only affect group 0.

2024-03-10 00:51 UTC, pcwalton commented on src/asset.rs
>          M: Modifier + Send + Sync + 'static,
Done

2024-03-10 00:52 UTC, pcwalton commented on src/modifier/clone.rs
> +    pub rate: f32,
Renamed to that.

2024-03-10 00:52 UTC, pcwalton commented on src/modifier/clone.rs
> +                let age_reset_code = if context.particle_layout().contains(Attribute::AGE) {
I documented it.

2024-03-10 00:57 UTC, pcwalton commented on src/render/mod.rs
> +    num_groups: u32,
Fixed

2024-03-10 00:58 UTC, pcwalton commented on src/render/mod.rs
> +    pub spawner_index: u32,
Removed

2024-03-10 00:58 UTC, pcwalton commented on src/render/vfx_indirect.wgsl
> +    let spawner_index = group_buffer[index].spawner_index;
Removed

2024-03-10 00:59 UTC, pcwalton commented
Addressed review comments.

2024-03-10 07:22 UTC, pcwalton commented on Cargo.toml
> +required-features = [ "bevy/bevy_winit", "bevy/bevy_pbr", "3d" ]
Done

2024-03-10 07:47 UTC, djeedai approved these changes
Merging as is, we can refine later if needed. Thanks a lot, this is an awesome change! 🥳

2024-03-10 07:47 UTC, djeedai commented on src/asset.rs
>      pub fn init_groups<M>(mut self, modifier: M, groups: ParticleGroupSet) -> Self
Does this make any sense if init modifiers can only be applied to group 0? Should we delete this, or at the very least panic that the group set is [0]?

2024-03-10 09:40 UTC, djeedai commented on src/asset.rs
>      pub fn init_groups<M>(mut self, modifier: M, groups: ParticleGroupSet) -> Self
Left the function signature for consistency, added a panic if the group is not `single(0)`.

2024-03-10 11:08 UTC, merged