Implement simple ribbon rendering.
djeedai/bevy_hanabi pull request #298
Opened 2024-03-11 10:14 UTC by pcwalton

This adds a new render modifier, the `RibbonModifier`. When it's present, quads are drawn between particles that are part of a trail created with the `CloneModifier`, instead of directly at the particle locations.

Internally, particles are threaded into a doubly linked list, with the `PREV` and `NEXT` attributes. I chose a linked list over fixed-size trails like the Unity VFX graph uses because (a) during ribbon rendering, a particle only needs to know the positions of its immediate neighbors; (b) linked lists better support variable-length trails. We need a doubly linked list instead of a singly linked list because (a) more sophisticated ribbon rendering will want to know about both the next and previous particles in order to implement line joins properly; (b) a singly linked list has difficulty dealing with dangling pointers to dead particles.

Each ribbon quad is initially oriented toward the average normal (`nlerp`) of the two particles that define it, modulo Gram-Schmidt normalization. Eventually, ribbon quads should be extended to support meshes with line joins, as well as perhaps curves, but the current approach should do for an initial implementation.

A new example, `ribbons`, has been added.

A screenshot *without* ribbons enabled:

<img width="962" alt="Screenshot 2024-03-11 024353" src="https://github.com/djeedai/bevy_hanabi/assets/157897/66a25655-72ac-4f99-8649-5564fd969da5">

And *with* ribbons enabled:

<img width="963" alt="Screenshot 2024-03-11 024412" src="https://github.com/djeedai/bevy_hanabi/assets/157897/4cc231bf-2a31-456c-bb37-75318c2d9173">

This is just a draft to get initial thoughts.

2024-03-13 04:41 UTC, pcwalton commented
I'm going to go ahead and mark this as ready for review.

Here's what the example looks like:

![Ribbon](https://github.com/djeedai/bevy_hanabi/assets/157897/15caf7b2-7dea-41bb-a8b3-79cc7c455073)

2024-03-13 08:09 UTC, pcwalton commented
I based this on top of #299, which should land first, because, in order to look right, this PR needs that PR.

2024-03-13 08:13 UTC, pcwalton commented
![Untitled video - Made with Clipchamp](https://github.com/djeedai/bevy_hanabi/assets/157897/f39832dc-87d5-4069-afdd-7312edc3ba3f)

2024-03-13 09:05 UTC, djeedai requested changes
The end result (example) looks good, but the use of a hard-coded flag is a bit unfortunate considering the context of me trying to remove those hard-coded codepaths from `RenderContext` so we can merge it with the init/update one, in favor of just having code generated from modifiers. I think that here we don't _need_ to have hard-coded `#ifdef`-based codegen, we can already mutate the variables of the shader by injecting the proper code from a modifier, no?

Also I don't understand the PR description stating we need both the next and prev attributes and a doubly linked list, but the render code and firework example seemingly using only the next attribute and not the prev one. Did I miss something? Each new attribute multiplied by the number of particles consumes some GPU RAM, so we should be careful about adding them.

2024-03-13 09:05 UTC, djeedai commented on src/render/vfx_render.wgsl
> +    let particle_size = vec2(length(delta), size.y);
We never use `PREV`. Why is the PR description stating that a doubly linked list is mandatory?

2024-03-15 16:13 UTC, pcwalton commented on examples/ribbon.rs
> +    let update_lifetime_attr = SetAttributeModifier {
Yeah, this is a bit of a design question. How do we specify "on-clone modifiers" that execute after a clone? They don't cleanly map to either init (which is for new particles, not cloned existing ones, and also don't expect to execute in `vfx_update.wgsl`) or to update (which run every frame). Do you have any ideas?

2024-03-15 17:09 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +    let particle_size = vec2(length(delta), size.y);
Oh, that was an older version, oops. I left the list as doubly linked because I thought that we'd need it to do [joins](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin) properly, but now that I think about it, it isn't necessary. I can make the list singly linked.

I didn't implement proper line joins in this PR because that requires changing the mesh topology from one quad to a quad plus a triangle (I think) and that's more involved. I figure that can be left to a followup.

2024-03-15 17:11 UTC, pcwalton commented on examples/ribbon.rs
> +    let update_lifetime_attr = SetAttributeModifier {
One thing I was thinking of is specifying a list of properties to reset in the `CloneModifier`, but it feels a bit limited compared to the variety of init modifiers we have.

2024-03-15 18:07 UTC, djeedai commented on examples/ribbon.rs
> +    let update_lifetime_attr = SetAttributeModifier {
Eventually we need to stop special casing clones, and run an init on all spawned particles, whether spawned from CPU or GPU. That will uniformize the two codepaths and fix this.

2024-03-16 05:44 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +    let particle_size = vec2(length(delta), size.y);
Are you sure? `PREV` has a performance cost, so I'd actually lean toward removing it if we don't see a use for it. We can always add it back later.

2024-03-17 10:30 UTC, djeedai commented on src/render/vfx_render.wgsl
> +    let particle_size = vec2(length(delta), size.y);
The existence of `Attribute::PREV` can stay without affecting the performance, if the attribute is not actually used for ribbons. It's simply available for use like all other attributes. I didn't mean keep a doubly linked list, I meant leave the definition of the attribute in case we need it in another context.

2024-03-20 16:41 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +    let particle_size = vec2(length(delta), size.y);
Hmm, seems like an odd decision, but I can do that.

2024-03-20 16:50 UTC, djeedai commented on src/render/vfx_render.wgsl
> +    let particle_size = vec2(length(delta), size.y);
There's already other existing attributes which are not used by any modifier, but are available for authors. Like for example all `Attribute::F32xx`.

2024-03-20 16:52 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +    let particle_size = vec2(length(delta), size.y);
Actually, you know what, I remembered that I need `PREV` here: https://github.com/djeedai/bevy_hanabi/pull/298/files#diff-dad29308145bd33a213e308666d22ddec33fac3aa47eef7561fe8d98cf85d4adR71 I use it to stitch the linked list properly.

It's not actually possible to have a singly linked list with only `next`. If we only have `next`, then when it comes time to clone a particle, there's no way for the head to find its most immediate follower particle to update its `next` pointer without a `prev` pointer.

The way to make a singly linked list would be to only have `prev`, where each particle points to its most immediate *follower*, not the particle that it's following. But that has the problem that the tail particle (the last particle in a trail) can end up with a dangling pointer to a dead particle. There's no way to fix that while still remaining singly linked, because particles that are about to die would have no way to find their next particle to update the pointer. In earlier version of this patch, the dangling pointers resulted in unsightly rendering glitches. This is why I had to move to a doubly linked list.

2024-03-20 16:53 UTC, pcwalton commented on examples/firework.rs
> +        attribute: Attribute::NEXT,
Oops, that was from an earlier version of this patch. I'll remove it.

2024-03-20 16:56 UTC, pcwalton commented on examples/ribbon.rs
> +    let update_lifetime_attr = SetAttributeModifier {
That would work, yeah, but we'll need to make sure all of the init modifiers work when their code is pasted into `vfx_update.wgsl`.

2024-03-20 22:35 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +    var sim_position: vec3<f32>;
Fixed.

2024-03-20 22:36 UTC, pcwalton commented on src/modifier/ribbon.rs
> +        context.ribbon = true;
I removed the flag.

2024-03-20 22:41 UTC, pcwalton commented on src/modifier/clone.rs
> +                    )
I split this into `prev` (previous link), `next` (next link), and `double` (both links present, to do the final node stitch).

2024-03-20 22:41 UTC, pcwalton commented
Comments addressed.

2024-03-22 21:45 UTC, djeedai commented on examples/ribbon.rs
> +    let update_lifetime_attr = SetAttributeModifier {
As far as I remember there's very little difference between the two passes (I just merged in #307 some more bind groups which were the same), but yes this needs some testing.

2024-03-22 21:51 UTC, djeedai approved these changes
Amazing, thanks a lot!

2024-03-22 21:52 UTC, merged