Allow particles to be arbitrary meshes.
djeedai/bevy_hanabi pull request #377
Opened 2024-09-20 04:25 UTC by pcwalton

TODO: Write more here.

2024-10-04 05:47 UTC, mmatvein approved these changes
I'm not an expert in the field, but I skimmed through the code and it looks good to me. I left two notes on things needed to get the CI to pass. It would be great to get this merged!

2024-10-04 05:47 UTC, mmatvein commented on src/render/mod.rs
> +    core_pipeline::core_3d::Opaque3d,
This will have to be moved under the `#[cfg(feature = "3d")]` section below to make the CI pass.

2024-10-04 05:47 UTC, mmatvein commented on src/render/mod.rs
>                  // Bevy uses reverse-Z, so Greater really means closer
This same thing will have to be done for the section starting at line 1261 to make the CI pass.

2024-10-05 21:53 UTC, djeedai requested changes
Mostly all good, just the thing on the normal transformation, and the one about the mutable reference to `Assets`. Aside from that looks all good. Thanks once again! :)

2024-10-05 21:53 UTC, djeedai commented on src/render/mod.rs
> +    pass.set_vertex_buffer(0, gpu_mesh.vertex_buffer.slice(..));
Just for my understanding, I assume Bevy is already managing storing the mesh into a vertex buffer? Is there any batching involved? (I assume there is from the `slice()` semantic)

2024-10-05 21:53 UTC, djeedai commented on src/render/vfx_render.wgsl
> +    return transform * sim_normal;
Shouldn't normals be transformed by the inverse transpose of the transform? https://stackoverflow.com/questions/13654401/why-transform-normals-with-the-transpose-of-the-inverse-of-the-modelview-matrix

2024-10-08 05:07 UTC, pcwalton commented on src/render/mod.rs
> +    pass.set_vertex_buffer(0, gpu_mesh.vertex_buffer.slice(..));
Bevy manages storing the mesh, yeah.

In 0.14 there isn't any batching involved, but in 0.15 there is. (That is, in 0.14 the buffer is guaranteed to contain only one mesh; in 0.15 Bevy might have stuffed other meshes into the same buffer.) So this code will have to be significantly modified once we upgrade to 0.15. Basically just copy the code from the `Opaque3d` implementation in upstream Bevy.

2024-10-08 07:17 UTC, pcwalton commented on src/plugin.rs
> +            EffectsMeta::new(render_device.clone(), &mut assets)
I'm not sure what you mean here. `EffectsMeta` doesn't keep a reference to the assets: it only adds `default_mesh` to the assets and then saves its handle (not the mesh itself).

2024-10-08 07:17 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +    return transform * sim_normal;
Good point, fixed.

2024-10-08 14:13 UTC, djeedai commented on src/render/mod.rs
> +    pass.set_vertex_buffer(0, gpu_mesh.vertex_buffer.slice(..));
Ah ok I missed that part sorry.

2024-10-08 14:13 UTC, djeedai commented on src/plugin.rs
> +            EffectsMeta::new(render_device.clone(), &mut assets)
Ah ok I missed that part sorry.

2024-11-02 23:04 UTC, pcwalton commented
@djeedai Updated.

2024-11-03 00:42 UTC, djeedai requested changes
Tried locally, the new puffs example is really nice!

Added a few comments, mostly minor things, but I think the normal transform is still wrong. Also can you please update the `CHANGELOG` as well as the various `build_examples` scripts?

If you're busy, I might consider merging as is and fixing after the fact, just because this touches quite a few files, to prevent further conflicts with other changes. Just let me know. Thanks!

2024-11-03 00:42 UTC, djeedai commented on src/render/mod.rs
> +    }
The index buffer is already set below.

2024-11-03 00:42 UTC, djeedai commented on src/render/mod.rs
> +impl ParticleRenderAlphaMaskPipelineKey {
Maybe use `impl From<LayoutFlags> for ParticleRenderAlphaMaskPipelineKey` instead? This sounds more idiomatic in Rust, no?

2024-11-03 00:42 UTC, djeedai commented on Cargo.toml
> +[dependencies.bevy_gltf]
Isn't that a `[dev-dependencies]` rather? It's only used in the `puffs.rs` example, isn't it?

2024-11-03 00:42 UTC, djeedai commented on Cargo.toml
> +    "bevy/bevy_winit",
This is missing `bevy/png` to load the fox texture.

2024-11-03 20:19 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +    let normal = mat3x3(axis_x, axis_y, axis_z) * vertex_normal;
OK, I added an `inverse_transpose_mat3` function. I don't love having to do this in the vertex shader, but I didn't want to bloat the particles just for that.

2024-11-03 20:30 UTC, pcwalton commented
@djeedai Updated.

2024-11-04 00:54 UTC, djeedai approved these changes

2024-11-04 01:58 UTC, merged