Unify the clone modifier and spawners, and fix races.
djeedai/bevy_hanabi pull request #387
Opened 2024-10-23 02:16 UTC by pcwalton

This large patch essentially makes particle trails and ribbons part of the spawner, which is processed during the init phase, rather than modifiers that execute during the update phase. Along the way, this made it easier to fix race conditions in spawning of trails, because spawning only happens in the init phase while despawning only happens in the update phase. This addresses #376, as well as underflow bugs that could occur in certain circumstances.

In detail, this commit makes the following changes:

* Every group now has an *initializer*. An initializer can either be a *spawner* or a *cloner*. This allows spawners to spawn into any group, not just the first one.

* The `EffectSpawner` component is now `EffectInitializers`, a component which contains the initializers for every group. Existing code that uses `EffectSpawner` can migrate by picking the first `EffectInitializer` from that component.

* The `CloneModifier` has been removed. Instead, use a `Cloner`, which manages the `age` and `lifetime` attributes automatically to avoid artifacts. The easiest way to create a cloner is to call `with_trails` or `with_ribbons` on your `EffectAsset`.

* The `RibbonModifier` has been removed. Instead, at most one of the groups may be delegated the ribbon group. The easiest way to delegate a ribbon group is to call `EffectAsset::with_ribbons`. (It may seem like a loss of functionality to only support one ribbon group, but it actually isn't, because there was only one `prev` and `next` attribute pair and so multiple ribbons never actually worked before.)

* The `capacity` parameter in `EffectAsset::new` is no longer a vector of capacities. Instead, you supply the capacity of each group as you create it. I figured this was cleaner.

* Init modifiers can now be specific to a particle group, and they execute for cloned particles as well. There's no need to use update modifiers to set values on cloned particles.

* Age and lifetime can no longer be set manually for cloned particles. (They can still be set as usual for spawned particles.) This enforces LIFO ordering for ribbons, which is necessary to avoid races.

* Underflow of particle counts that could occur in certain scenarios involving multiple groups is fixed. The racy hack that "put back" particles that would otherwise underflow the alive count is no longer needed.

* Particle linked lists no longer race with one another (#376).

Closes #376.

2024-10-23 12:03 UTC, djeedai commented on src/render/mod.rs
> +                        is_trail: group_index > 0,
Is that always true? I thought there's another comment about "only support one trail or ribbon". That means there can only ever be up to 2 groups per effect, right?

2024-10-23 12:05 UTC, djeedai commented on src/render/mod.rs
> -    if effects_meta.spawner_buffer.buffer().is_none() || effects_meta.spawner_buffer.is_empty() {
Why remove this? If I recall correctly this was needed to avoid some `unwrap()` panic later, which admittedly might have been fixed and is not the root cause, but is safer anyway, no? Because having a spawner buffer allocated is a hard requirement for any effect at all to be active.

2024-10-23 12:09 UTC, djeedai commented on src/render/mod.rs
> +        // @binding(1) var<storage, read_write> render_group_indirect : RenderGroupIndirect
```suggestion
        // @binding(1) var<storage, read_write> dest_render_group_indirect : RenderGroupIndirect
```

(this makes it easier to find the Rust code associated with the shader code if we keep the names consistent)

2024-10-23 12:09 UTC, djeedai commented on src/render/mod.rs
> +        // @binding(2) var<storage, read_write> render_group_indirect : RenderGroupIndirect
```suggestion
        // @binding(2) var<storage, read_write> src_render_group_indirect : RenderGroupIndirect
```

2024-10-23 12:13 UTC, djeedai commented on src/render/mod.rs
> +                                // total_group_count += batches.group_batches.len() as u32;
Note: #383 fixes this (I can hold on to it to prevent conflicts, this PR is more important).

2024-10-23 12:16 UTC, djeedai commented on src/render/mod.rs
> +                                        render_group_indirect_offset as u32,
Shouldn't there be only 2 offsets / no source when there's a spawner? Is this just out of simplicity we bind and ignore an extra buffer in the case of spawner?

2024-10-23 17:23 UTC, pcwalton commented on src/render/vfx_common.wgsl
> +const S_OFFSET_CLONE_SRC_GROUP: u32 = 30u;
Oops, remnant from an old version of the patch. Removed.

2024-10-23 17:23 UTC, pcwalton commented on src/render/vfx_common.wgsl
> +const REM_OFFSET_MAX_CLONE: u32 = 1u;
Oops, remnant from an old version of the patch. Removed.

2024-10-23 17:46 UTC, pcwalton commented on src/asset.rs
> +        self.capacities.push(capacity);
You can have as many trails as you want though.

2024-10-23 20:58 UTC, pcwalton commented on src/spawn.rs
> +    pub spawn_this_frame: bool,
`spawn_this_frame` is used in `VfxSimulateNode::run` to check to see whether we're going to run the cloner.

2024-10-23 21:01 UTC, pcwalton commented on src/render/vfx_update.wgsl
> +        // There's no worry about races here, because the trails are all in a
This is when a head particle leading a ribbon dies.

2024-10-23 21:06 UTC, pcwalton commented on src/asset.rs
> +        self.capacities.push(capacity);
You can have as many trails as you want. I added a debug-mode check in `EffectAsset::with_ribbons` though.

2024-10-23 21:11 UTC, pcwalton commented on src/render/vfx_render.wgsl
> +        out.position = vec4(0.0);
I tried to make an infinite value by using 1.0 / 0.0, but I got `failed to convert expression to a concrete type: the concrete type f32 cannot represent the abstract value inf accurately`. Not sure if this is a Naga bug or what.

2024-10-23 21:15 UTC, pcwalton commented on src/render/vfx_init.wgsl
> +@group(3) @binding(2) var<storage, read_write> src_render_group_indirect: RenderGroupIndirect;
Yes, it's because of the atomic load.

2024-10-23 21:16 UTC, pcwalton commented on src/render/vfx_init.wgsl
> +    let max_spawn = atomicLoad(&src_render_group_indirect.max_spawn);
Oh yes, good point, it should be `max_spawn` of the destination group in both cases.

2024-10-23 21:17 UTC, Seldom-SE reviewed
Thanks for the rework, I like the API changes! I tried out this PR, and I've noticed some differences that I think are notable:

- Since trail lifetimes are `CpuValue`s, their lifetimes can't be configured via properties. Not a big issue, to be clear, I'll just make separate effect assets when I need a different lifetime.
- My effects spawn a single particle in group 0, but now I need at least a group 0 capacity of 2 for the particles to show up at all
- Now many attributes (including `POSITION` and `HDR_COLOR`, but excluding `AGE`) must be initialized in `init` instead of just being set in `update`

I've also still noticed lag and artifacts like in #376, see the end of this video:

https://github.com/user-attachments/assets/4d030c24-acaf-4e90-85ef-0ac2e83e79b8

I didn't read through these changes, just left comments on some things I noticed

2024-10-23 21:17 UTC, Seldom-SE commented on src/asset.rs
> +    pub fn new(capacity: u32, spawner: Spawner, module: Module) -> Self {
The docs on this function still reference `CloneModifier`

2024-10-23 21:17 UTC, Seldom-SE commented on src/asset.rs
> +    /// cloned.
Now that this is the case, perhaps `init`'s groups could be `ParticleGroupSet::all()` like in `update`

2024-10-23 21:19 UTC, pcwalton commented on src/render/vfx_init.wgsl
> +    dest_base_index += particle_groups[{{DEST_GROUP_INDEX}}].indirect_index;
Removed the `CLONE` ifdef.

2024-10-23 21:21 UTC, pcwalton commented on src/render/mod.rs
> +            label: Some("hanabi:pipeline_clone_compute".into()),
Oops, yeah, that was from a previous version of the patch.

2024-10-23 21:35 UTC, pcwalton commented on src/render/mod.rs
> +    pad: [u32; 3],
If I remove `pad` then I get:
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> src\render\mod.rs:261:19
    |
261 | pub(crate) struct GpuSpawnerParams {
    |                   ^^^^^^^^^^^^^^^^
    |
    = note: source type: `render::GpuSpawnerParams` (1024 bits)
    = note: target type: `render::_::{closure#0}::TypeWithoutPadding` (928 bits)
```
That's why I added `pad` in the first place.

2024-10-23 21:47 UTC, pcwalton commented on src/render/mod.rs
> +                                        render_group_indirect_offset as u32,
Yes. It saves us having to have two different bind group layouts, etc.

2024-10-23 21:53 UTC, pcwalton commented on src/lib.rs
> +    pub init: Vec<Handle<Shader>>,
I moved all the shaders for each group together as suggested.

2024-10-23 22:00 UTC, pcwalton commented on src/asset.rs
> +            set.insert(Attribute::PREV);
Done.

2024-10-23 22:00 UTC, pcwalton commented on src/render/vfx_init.wgsl
> +    particle.prev = 0xffffffffu;
You're right. I changed it as suggested.

2024-10-23 22:01 UTC, pcwalton commented on src/render/vfx_init.wgsl
> +    let max_spawn = atomicLoad(&src_render_group_indirect.max_spawn);
Fixed.

2024-10-23 22:02 UTC, pcwalton commented on src/render/mod.rs
> +            render_device: (*render_device).clone(),
Removed.

2024-10-23 22:03 UTC, pcwalton commented on src/render/mod.rs
> +    /// the effect.
I reworded it.

2024-10-23 22:03 UTC, pcwalton commented on src/render/mod.rs
> +                        is_trail: group_index > 0,
Oh right, that was from an earlier version of the patch. Fixed.

2024-10-23 22:03 UTC, pcwalton commented on src/render/mod.rs
> -    if effects_meta.spawner_buffer.buffer().is_none() || effects_meta.spawner_buffer.is_empty() {
I put it back.

2024-10-23 22:03 UTC, pcwalton commented on src/asset.rs
> +    /// cloned.
I made this change.

2024-10-23 22:04 UTC, pcwalton commented on src/asset.rs
> +    pub fn new(capacity: u32, spawner: Spawner, module: Module) -> Self {
I removed the reference.

2024-10-23 22:04 UTC, pcwalton commented
Comments addressed.

2024-10-24 13:25 UTC, chronicl commented
Great PR!
However, the "worms" example is broken for me. Could you check that out?

2024-10-24 20:01 UTC, pcwalton commented
Fixed.

2024-10-25 08:40 UTC, djeedai commented on src/render/vfx_render.wgsl
> +        out.position = vec4(0.0);
We can always use `1e25` that's probably far enough 😆

2024-10-25 08:41 UTC, djeedai commented on src/asset.rs
> +        self.capacities.push(capacity);
By "as many trails as you want", does that mean "one shared head and N trails, total N+1 groups"?

2024-10-25 08:45 UTC, djeedai commented on src/asset.rs
> +        self.capacities.push(capacity);
Ok the doc of `with_trails()` clarifies that indeed.

2024-10-25 09:01 UTC, djeedai commented on src/render/mod.rs
> +    pad: [u32; 3],
Ok I tried locally, that's because `Pod` requires no (implicit) padding, but because of `Vec4` inside `GpuCompressedTransform` the struct align is 16 bytes. So we need manual padding to make `Pod` happy. That error message is quite obscure.

2024-10-25 09:20 UTC, djeedai approved these changes
Looks all good to me, but I'd like for @Seldom-SE to confirm that the lags are gone before merging, because that was the entire point of this change (or part of it at least).

Also @pcwalton can you please consider avoiding force-push in the future, especially on large PRs like this? In general with git this doesn't work well with PRs, but here the GitHub UI is rather bad, and I can only see the difference between your previous and current version at the file level (whether the file was modified or not, as a boolean state), not at the line level (_what_ actually changed). So each time I have to review 3000 lines again to figure out what changed in `render/mod.rs` for example 😢 At least with incremental commits I can look at just the newer commits. I'll squash on merge anyway (unless there's a strong reason to keep history, but that's very rare). Thanks!

2024-10-26 04:28 UTC, Seldom-SE approved these changes
> I'd like for @Seldom-SE to confirm that the lags are gone before merging

This PR fixes some long random freezes we were running into, but doesn't fix the constant low FPS at about 750 particles. I'm getting FPS lows in the same ballpark (1-4.5) in a given situation in our game. Whatever's causing that lag is likely out of scope for this PR, and I'm not seeing the ribbon artifacts anymore, so I think this is good to merge.

Thanks!

2024-10-26 09:15 UTC, djeedai commented
The following examples are broken:
- `spawn_on_command`
- `activate`
- `force_field`

Also the `ribbon` example at start looks like it has 2 particles attached to the same root:

<img width="639" alt="ribbon" src="https://github.com/user-attachments/assets/bce3a011-c221-428c-a34b-d6a0cba2dfa0">

2024-10-26 23:29 UTC, pcwalton commented
Fixed. See the commit message for more details as to what was going wrong.

2024-10-27 10:31 UTC, djeedai requested changes

2024-10-27 10:31 UTC, djeedai commented on src/spawn.rs
> +#[allow(missing_copy_implementations)]
Any change we keep the `Copy` if possible? It seems the bug was just the missing `ref`, no?

2024-10-27 10:31 UTC, djeedai commented on src/spawn.rs
> +            EffectInitializer::Spawner(ref mut effect_spawner) => effect_spawner.reset(),
Can't we just `match self` to get a reference to the inner directly? I don't see the point of matching `*self` then adding a `ref` (but I'm not super familiar with the use of `ref`).

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8f3773914decdad16ff40febccbf59c6

2024-10-27 10:31 UTC, djeedai commented on src/render/vfx_init.wgsl
> +    let spawn_count: u32 = src_render_group_indirect.max_update;
But this is wrong I think. `max_update` is the number of alive particles (in the head group, since it's the source one) _before_ the Update pass. After it, some particles might have died. So `alive_count <= max_update` but not necessarily equal at the end of the Update pass. This means on next frame we might clone more particles than there are head particles alive.

2024-10-27 21:10 UTC, pcwalton commented
Ok, I fixed the problem by reverting to `alive_count` and instead sorting the groups so that we evaluate cloners before spawners.

2024-10-29 08:01 UTC, djeedai approved these changes

2024-10-29 08:02 UTC, merged